// Package gogen emits the Go server half of a sigil contract — the
// `go` target of `sigil gen`.
//
// One sigil package → one generated Go file containing:
//
//   - struct definitions for each declared `type` (records → struct,
//     all-unit sums → string-typed const enum, payload-carrying sums →
//     a discriminated-union tagged struct + constructors + a
//     `{tag, value}` JSON codec)
//   - one `<Op>Request` struct per query / command / stream (always
//     generated, even for zero-arg ops, so the JSON-decode wire
//     shape is uniform)
//   - one typed stream sender per stream op: multi-channel streams
//     get one method per channel (`ChatStream.Thinking(text)`),
//     scalar streams get `Send(text)` — channel names can't typo and
//     NDJSON framing is invisible to the implementor
//   - one service interface per declared backend (named after it),
//     with one method per op routed through that backend
//   - one `New<Backend>Handler(impl, opts...) http.Handler` per
//     backend: routes `POST /query|/command|/stream/<Op>`, decodes +
//     validates (400 on shape errors), and owns stream framing and
//     error mapping — the exact rules the generated client expects.
//     Before calling the impl it injects serve.WithResponse(...) on
//     the request context, so an impl can reach serve.ResponseFrom(ctx)
//     to read request metadata (headers, cookies) and write response
//     metadata (Set-Cookie, headers) without the method signatures
//     carrying the http.ResponseWriter
//   - `NewPageHandler` serving the compiled app page (boot-time
//     compile via pkg/serve, contract-hash verified)
//   - `const ContractHash` — the wire-shape digest stamped at
//     generation time; NewPageHandler recomputes it from the freshly
//     compiled package at boot and refuses to start on a mismatch,
//     so server code generated by one sigil version can never
//     silently serve a client bundle compiled by another
//
// Error mapping for streams (the wire contract's hard rules):
//
//   - impl returns an error before any delta was written → the
//     response becomes a 502 with the error text, so the client's
//     `<Op>.failed` / `<Op>.error` cells trip
//   - impl returns an error after deltas were written → multi-channel
//     streams emit a final `{"channel":"__error","text":…}` line
//     (the generated client recognizes the reserved channel and
//     fails the op); scalar streams just close — raw text has no
//     in-band frame to carry an error
//
// Type mapping:
//
//	Int     → int64
//	String  → string
//	Bool    → bool
//	List<T> → []T
//	T?      → *T   (slices stay []T — they're already nilable)
//	declared record → Go struct
//	declared sum    → custom string type with consts
//
// gogen is a pure transform over contract.Contract — no filesystem,
// no flags. It registers itself as the "go" target in pkg/gen's
// registry; the CLI plumbing lives in internal/cli.
package gogen

import (
	"fmt"
	"go/format"
	"strings"

	"github.com/incantery/mako/pkg/contract"
	"github.com/incantery/mako/pkg/gen"
	"github.com/incantery/mako/pkg/ir"
)

// ErrorChannel is the reserved stream channel that carries a
// mid-stream failure to the client. Implementations can't collide
// with it — sigil field names never start with underscores.
const ErrorChannel = "__error"

// target is the pkg/gen registry entry.
type target struct{}

func (target) Name() string { return "go" }

func (target) Generate(req gen.Request) ([]gen.File, error) {
	pkgName := req.Opts["package"]
	if pkgName == "" {
		pkgName = goPackageName(req.Out)
	}
	src, err := Emit(req.Contract, pkgName, req.Hash)
	if err != nil {
		return nil, err
	}
	return []gen.File{{Path: "sigil.gen.go", Content: []byte(src)}}, nil
}

func init() { gen.Register(target{}) }

// goPackageName derives a Go package name from the entry's out dir
// ("internal/gen/chat" → "chat"), sanitized to a legal identifier.
func goPackageName(out string) string {
	base := out
	if i := strings.LastIndexAny(base, "/\\"); i >= 0 {
		base = base[i+1:]
	}
	var b strings.Builder
	for _, r := range base {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r == '_':
			b.WriteRune(r)
		case r >= '0' && r <= '9' && b.Len() > 0:
			b.WriteRune(r)
		}
	}
	if b.Len() == 0 {
		return "api"
	}
	return strings.ToLower(b.String())
}

// opGroup is one backend's slice of the contract: the ops that route
// through it. groupName is the Go interface name (the backend's name,
// or "API" for ops bound to no backend in a backend-less program).
type opGroup struct {
	name     string
	queries  []ir.Query
	commands []ir.Command
	streams  []ir.Stream
}

// Emit returns the generated Go source for the contract. pkgName
// names the Go package; hash is the contract digest stamped into the
// ContractHash const (pass contract.Hash() — pkg/gen's runner does).
func Emit(c contract.Contract, pkgName, hash string) (string, error) {
	if pkgName == "" {
		return "", fmt.Errorf("gogen: package name is required")
	}
	if c.Empty() {
		return "", fmt.Errorf("gogen: no queries, commands, or streams declared — nothing to serve")
	}
	groups, err := groupOps(c)
	if err != nil {
		return "", err
	}

	var b strings.Builder
	writeHeader(&b, pkgName, headerNeeds{
		fmt:     validatorsErr(c),
		sync:    len(c.Streams) > 0,
		streams: len(c.Streams) > 0,
	})
	fmt.Fprintf(&b, "// ContractHash is the wire-shape digest of the sigil contract this\n")
	fmt.Fprintf(&b, "// file was generated from. NewPageHandler verifies the compiled\n")
	fmt.Fprintf(&b, "// package still matches it at boot.\n")
	fmt.Fprintf(&b, "const ContractHash = %q\n\n", hash)

	writeTypeDecls(&b, c.Types)
	for _, g := range groups {
		writeRequestStructs(&b, g)
	}
	if len(c.Streams) > 0 {
		writeStreamWriter(&b)
		for _, s := range c.Streams {
			writeStreamSender(&b, s)
		}
	}
	for _, g := range groups {
		writeInterface(&b, g)
	}
	writeValidators(&b, c)
	writeHandlerOptions(&b)
	for _, g := range groups {
		writeHandlerConstructor(&b, g)
	}
	writePageHandler(&b)

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		return "", fmt.Errorf("gogen: generated source does not gofmt (generator bug): %w", err)
	}
	return string(src), nil
}

// groupOps splits the contract's ops by backend. Deterministic
// order: backends in declaration order, then the no-backend group
// (named API) if any op is unbound.
func groupOps(c contract.Contract) ([]opGroup, error) {
	byName := map[string]*opGroup{}
	var order []*opGroup
	group := func(backend string) *opGroup {
		name := backend
		if name == "" {
			name = "API"
		}
		if g, ok := byName[name]; ok {
			return g
		}
		g := &opGroup{name: name}
		byName[name] = g
		order = append(order, g)
		return g
	}
	// Seed declared backends first so group order follows source.
	for _, b := range c.Backends {
		group(b.Name)
	}
	for _, q := range c.Queries {
		g := group(q.Backend)
		g.queries = append(g.queries, q)
	}
	for _, cmd := range c.Commands {
		g := group(cmd.Backend)
		g.commands = append(g.commands, cmd)
	}
	for _, s := range c.Streams {
		g := group(s.Backend)
		g.streams = append(g.streams, s)
	}
	// Drop backends that own no ops — nothing to generate for them.
	var out []opGroup
	for _, g := range order {
		if len(g.queries)+len(g.commands)+len(g.streams) == 0 {
			continue
		}
		out = append(out, *g)
	}
	// Guard nameability hazards. Generated decls are package-global,
	// so the op set must not collide across these axes — sigil allows
	// each individually, but Go would see duplicate top-level decls
	// and gofmt/build would fail with a confusing error far from the
	// source. Catch them here with a precise message.
	declared := map[string]bool{}
	for _, t := range c.Types {
		declared[t.Name] = true
	}
	for _, s := range c.Streams {
		if declared[s.Name+"Stream"] {
			return nil, fmt.Errorf("gogen: declared type %q collides with the generated sender type for stream %q", s.Name+"Stream", s.Name)
		}
	}
	// (a) A type named <Op>Request collides with the generated
	// request struct; (b) two ops sharing a name across kinds (a
	// query and a command both named Foo — legal in sigil, separate
	// namespaces) generate one FooRequest / validateFooRequest twice.
	opKind := map[string]string{}
	for _, name := range opNames(c) {
		if declared[name+"Request"] {
			return nil, fmt.Errorf("gogen: declared type %q collides with the request struct generated for op %q — rename one", name+"Request", name)
		}
	}
	check := func(kind, name string) error {
		if prev, dup := opKind[name]; dup {
			return fmt.Errorf("gogen: op name %q is used by both a %s and a %s — the generated Go server needs op names unique across kinds; rename one", name, prev, kind)
		}
		opKind[name] = kind
		return nil
	}
	for _, q := range c.Queries {
		if err := check("query", q.Name); err != nil {
			return nil, err
		}
	}
	for _, cmd := range c.Commands {
		if err := check("command", cmd.Name); err != nil {
			return nil, err
		}
	}
	for _, s := range c.Streams {
		if err := check("stream", s.Name); err != nil {
			return nil, err
		}
	}
	return out, nil
}

// opNames returns every op's name across all kinds, in a stable
// order (queries, commands, streams).
func opNames(c contract.Contract) []string {
	var names []string
	for _, q := range c.Queries {
		names = append(names, q.Name)
	}
	for _, cmd := range c.Commands {
		names = append(names, cmd.Name)
	}
	for _, s := range c.Streams {
		names = append(names, s.Name)
	}
	return names
}

type headerNeeds struct {
	fmt     bool
	sync    bool
	streams bool
}

// writeHeader emits the `Code generated…` line, package clause, and
// the import set. context / encoding/json / net/http / pkg/serve are
// always in scope; fmt only when a validator returns an error; sync
// only when stream senders exist.
func writeHeader(b *strings.Builder, pkgName string, needs headerNeeds) {
	b.WriteString("// Code generated by sigil gen. DO NOT EDIT.\n")
	fmt.Fprintf(b, "package %s\n\n", pkgName)
	b.WriteString("import (\n")
	b.WriteString("\t\"context\"\n")
	b.WriteString("\t\"encoding/json\"\n")
	if needs.fmt {
		b.WriteString("\t\"fmt\"\n")
	}
	b.WriteString("\t\"net/http\"\n")
	if needs.sync {
		b.WriteString("\t\"sync\"\n")
	}
	b.WriteString("\n\t\"github.com/incantery/mako/pkg/serve\"\n")
	b.WriteString(")\n\n")
}

// writeTypeDecls emits Go type declarations for each declared type.
// Records become structs. A plain (all-unit) sum becomes a custom
// string type + one const per variant. A payload-carrying sum becomes
// a discriminated-union tagged struct + constructors + a JSON codec
// for the `{tag, value}` wire shape (writeUnionType). Order matches
// the contract so the output is stable.
func writeTypeDecls(b *strings.Builder, types []ir.TypeDecl) {
	for _, t := range types {
		switch t.Kind {
		case "record":
			fmt.Fprintf(b, "type %s struct {\n", t.Name)
			for _, f := range t.Fields {
				fmt.Fprintf(b, "\t%s %s `json:\"%s%s\"`\n",
					goFieldName(f.Name), goType(f.Type), f.Name, jsonTagSuffix(f.Type))
			}
			b.WriteString("}\n\n")
		case "sum":
			if t.HasPayloads() {
				writeUnionType(b, t)
				continue
			}
			fmt.Fprintf(b, "type %s string\n\n", t.Name)
			b.WriteString("const (\n")
			for _, v := range t.Variants {
				fmt.Fprintf(b, "\t%s%s %s = %q\n",
					t.Name, goFieldName(v), t.Name, v)
			}
			b.WriteString(")\n\n")
		}
	}
}

// writeUnionType emits the Go representation of a discriminated union:
// a tagged struct (Tag + one pointer field per payloaded variant),
// one New<Union><Variant> constructor each, and MarshalJSON/Unmarshal
// JSON implementing the `{tag, value}` wire shape — the same shape the
// generated client cell holds, so a server-built variant round-trips
// straight into the matching `match` arm.
func writeUnionType(b *strings.Builder, t ir.TypeDecl) {
	fmt.Fprintf(b, "// %s is a discriminated union: exactly one variant is set,\n", t.Name)
	fmt.Fprintf(b, "// named by Tag. Build it with the New%s* constructors.\n", t.Name)
	fmt.Fprintf(b, "type %s struct {\n", t.Name)
	b.WriteString("\tTag string\n")
	for _, v := range t.VariantSpecs {
		if v.Payload == nil {
			continue
		}
		fmt.Fprintf(b, "\t%s *%s\n", goFieldName(v.Name), goType(*v.Payload))
	}
	b.WriteString("}\n\n")

	// Constructors.
	for _, v := range t.VariantSpecs {
		if v.Payload == nil {
			fmt.Fprintf(b, "func New%s%s() %s { return %s{Tag: %q} }\n\n",
				t.Name, goFieldName(v.Name), t.Name, t.Name, v.Name)
			continue
		}
		fmt.Fprintf(b, "func New%s%s(v %s) %s { return %s{Tag: %q, %s: &v} }\n\n",
			t.Name, goFieldName(v.Name), goType(*v.Payload), t.Name, t.Name, v.Name, goFieldName(v.Name))
	}

	// MarshalJSON: emit `{tag, value}` with value being the active
	// variant's payload (omitted for a unit variant).
	fmt.Fprintf(b, "func (u %s) MarshalJSON() ([]byte, error) {\n", t.Name)
	b.WriteString("\tvar value any\n")
	b.WriteString("\tswitch u.Tag {\n")
	for _, v := range t.VariantSpecs {
		fmt.Fprintf(b, "\tcase %q:\n", v.Name)
		if v.Payload != nil {
			fmt.Fprintf(b, "\t\tif u.%s != nil {\n\t\t\tvalue = *u.%s\n\t\t}\n", goFieldName(v.Name), goFieldName(v.Name))
		}
	}
	b.WriteString("\tdefault:\n")
	fmt.Fprintf(b, "\t\treturn nil, fmt.Errorf(\"%s: unknown tag %%q\", u.Tag)\n", t.Name)
	b.WriteString("\t}\n")
	b.WriteString("\treturn json.Marshal(struct {\n")
	b.WriteString("\t\tTag   string `json:\"tag\"`\n")
	b.WriteString("\t\tValue any    `json:\"value,omitempty\"`\n")
	b.WriteString("\t}{u.Tag, value})\n")
	b.WriteString("}\n\n")

	// UnmarshalJSON: read the tag, decode value into the right field.
	fmt.Fprintf(b, "func (u *%s) UnmarshalJSON(data []byte) error {\n", t.Name)
	b.WriteString("\tvar w struct {\n")
	b.WriteString("\t\tTag   string          `json:\"tag\"`\n")
	b.WriteString("\t\tValue json.RawMessage `json:\"value\"`\n")
	b.WriteString("\t}\n")
	b.WriteString("\tif err := json.Unmarshal(data, &w); err != nil {\n\t\treturn err\n\t}\n")
	b.WriteString("\tu.Tag = w.Tag\n")
	b.WriteString("\tswitch w.Tag {\n")
	for _, v := range t.VariantSpecs {
		fmt.Fprintf(b, "\tcase %q:\n", v.Name)
		if v.Payload != nil {
			fmt.Fprintf(b, "\t\tvar v %s\n", goType(*v.Payload))
			b.WriteString("\t\tif len(w.Value) > 0 {\n")
			b.WriteString("\t\t\tif err := json.Unmarshal(w.Value, &v); err != nil {\n\t\t\t\treturn err\n\t\t\t}\n")
			b.WriteString("\t\t}\n")
			fmt.Fprintf(b, "\t\tu.%s = &v\n", goFieldName(v.Name))
		}
	}
	b.WriteString("\tdefault:\n")
	fmt.Fprintf(b, "\t\treturn fmt.Errorf(\"%s: unknown tag %%q\", w.Tag)\n", t.Name)
	b.WriteString("\t}\n")
	b.WriteString("\treturn nil\n")
	b.WriteString("}\n\n")
}

// writeRequestStructs emits one `<Name>Request` struct per op in the
// group (queries, commands, then streams — source order within each
// kind). Zero-arg ops still get an empty struct so the dispatch code
// is uniform: decode into a struct, call method, encode result.
func writeRequestStructs(b *strings.Builder, g opGroup) {
	for _, q := range g.queries {
		writeOneRequestStruct(b, q.Name, q.Inputs)
	}
	for _, c := range g.commands {
		writeOneRequestStruct(b, c.Name, c.Inputs)
	}
	for _, s := range g.streams {
		writeOneRequestStruct(b, s.Name, s.Inputs)
	}
}

func writeOneRequestStruct(b *strings.Builder, opName string, inputs []ir.TypeFieldSpec) {
	if len(inputs) == 0 {
		fmt.Fprintf(b, "type %sRequest struct{}\n\n", opName)
		return
	}
	fmt.Fprintf(b, "type %sRequest struct {\n", opName)
	for _, in := range inputs {
		fmt.Fprintf(b, "\t%s %s `json:\"%s%s\"`\n",
			goFieldName(in.Name), goType(in.Type), in.Name, jsonTagSuffix(in.Type))
	}
	b.WriteString("}\n\n")
}

// writeStreamWriter emits the one shared low-level writer all typed
// stream senders delegate to. It owns the only mutable streaming
// state — whether anything was written yet (the 502-vs-mid-stream
// pivot) — and serializes writes so implementations may emit from
// multiple goroutines.
func writeStreamWriter(b *strings.Builder) {
	b.WriteString(`// streamWriter is the shared low-level delta writer behind every
// typed stream sender. Write order is serialized; wrote flips on the
// first delta and decides the error mapping (502 before the first
// delta, in-band after).
type streamWriter struct {
	w     http.ResponseWriter
	fl    http.Flusher
	mu    sync.Mutex
	wrote bool
}

func (s *streamWriter) writeChannel(channel, text string) error {
	b, err := json.Marshal(struct {
		Channel string ` + "`json:\"channel\"`" + `
		Text    string ` + "`json:\"text\"`" + `
	}{channel, text})
	if err != nil {
		return err
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	s.wrote = true
	if _, err := s.w.Write(append(b, '\n')); err != nil {
		return err
	}
	s.fl.Flush()
	return nil
}

func (s *streamWriter) writeRaw(text string) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.wrote = true
	if _, err := s.w.Write([]byte(text)); err != nil {
		return err
	}
	s.fl.Flush()
	return nil
}

func (s *streamWriter) sawWrite() bool {
	s.mu.Lock()
	defer s.mu.Unlock()
	return s.wrote
}

`)
}

// writeStreamSender emits the typed sender for one stream op.
// Multi-channel streams get one method per declared channel; scalar
// streams get Send. The wire framing lives entirely in streamWriter,
// so an implementor physically cannot mis-frame or typo a channel.
func writeStreamSender(b *strings.Builder, s ir.Stream) {
	tn := s.Name + "Stream"
	if len(s.Channels) > 0 {
		fmt.Fprintf(b, "// %s sends %s deltas. Each method writes one NDJSON line\n", tn, s.Name)
		fmt.Fprintf(b, "// tagged with its channel and flushes it to the client.\n")
		fmt.Fprintf(b, "type %s struct {\n\ts *streamWriter\n}\n\n", tn)
		for _, ch := range s.Channels {
			fmt.Fprintf(b, "func (s *%s) %s(text string) error {\n", tn, goFieldName(ch))
			fmt.Fprintf(b, "\treturn s.s.writeChannel(%q, text)\n", ch)
			b.WriteString("}\n\n")
		}
		return
	}
	fmt.Fprintf(b, "// %s sends %s deltas: raw text chunks, appended verbatim\n", tn, s.Name)
	fmt.Fprintf(b, "// by the client.\n")
	fmt.Fprintf(b, "type %s struct {\n\ts *streamWriter\n}\n\n", tn)
	fmt.Fprintf(b, "func (s *%s) Send(text string) error {\n\treturn s.s.writeRaw(text)\n}\n\n", tn)
}

// writeInterface emits one service interface per backend group —
// the contract a hand-written server implements. Streams take their
// typed sender as the third parameter and return only error: the
// stream IS the result.
func writeInterface(b *strings.Builder, g opGroup) {
	fmt.Fprintf(b, "// %s is the server contract for every op routed through the\n", g.name)
	fmt.Fprintf(b, "// %q backend. Implement it, then mount New%sHandler.\n", g.name, g.name)
	fmt.Fprintf(b, "type %s interface {\n", g.name)
	for _, q := range g.queries {
		fmt.Fprintf(b, "\t%s(ctx context.Context, req %sRequest) (%s, error)\n",
			q.Name, q.Name, goType(q.Return))
	}
	for _, c := range g.commands {
		fmt.Fprintf(b, "\t%s(ctx context.Context, req %sRequest) (%s, error)\n",
			c.Name, c.Name, goType(c.Return))
	}
	for _, s := range g.streams {
		fmt.Fprintf(b, "\t%s(ctx context.Context, req %sRequest, stream *%sStream) error\n",
			s.Name, s.Name, s.Name)
	}
	b.WriteString("}\n\n")
}

// writeHandlerOptions emits the option plumbing shared by every
// generated handler constructor: whole-handler middleware (the v1
// seam — auth, logging, CORS wrap here) and a request-body cap.
func writeHandlerOptions(b *strings.Builder) {
	b.WriteString(`// HandlerOption configures a generated handler.
type HandlerOption func(*handlerConfig)

type handlerConfig struct {
	middleware      []func(http.Handler) http.Handler
	maxRequestBytes int64
}

// WithMiddleware wraps the whole handler. Options apply outermost
// first: WithMiddleware(a), WithMiddleware(b) yields a(b(handler)).
func WithMiddleware(mw func(http.Handler) http.Handler) HandlerOption {
	return func(c *handlerConfig) { c.middleware = append(c.middleware, mw) }
}

// WithMaxRequestBytes caps op request bodies (default 1 MiB).
func WithMaxRequestBytes(n int64) HandlerOption {
	return func(c *handlerConfig) { c.maxRequestBytes = n }
}

func newHandlerConfig(opts []HandlerOption) handlerConfig {
	cfg := handlerConfig{maxRequestBytes: 1 << 20}
	for _, o := range opts {
		o(&cfg)
	}
	return cfg
}

func (c handlerConfig) wrap(h http.Handler) http.Handler {
	for i := len(c.middleware) - 1; i >= 0; i-- {
		h = c.middleware[i](h)
	}
	return h
}

// decodeRequest decodes + caps one op request body. A false return
// means the 400 response was already written.
func decodeRequest(w http.ResponseWriter, r *http.Request, maxBytes int64, into any) bool {
	r.Body = http.MaxBytesReader(w, r.Body, maxBytes)
	if err := json.NewDecoder(r.Body).Decode(into); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return false
	}
	return true
}

`)
}

// writeHandlerConstructor emits New<Backend>Handler: an http.Handler
// routing POST /query|/command|/stream/<Op> with decode → validate →
// dispatch, plus the stream error mapping the generated client
// expects.
func writeHandlerConstructor(b *strings.Builder, g opGroup) {
	fmt.Fprintf(b, "// New%sHandler returns the HTTP handler implementing the wire\n", g.name)
	fmt.Fprintf(b, "// contract for %s's ops. Mount it wherever your mux routes\n", g.name)
	fmt.Fprintf(b, "// /query/, /command/, and /stream/ paths.\n")
	fmt.Fprintf(b, "func New%sHandler(impl %s, opts ...HandlerOption) http.Handler {\n", g.name, g.name)
	b.WriteString("\tcfg := newHandlerConfig(opts)\n")
	b.WriteString("\tmux := http.NewServeMux()\n")
	for _, q := range g.queries {
		writeUnaryHandler(b, "query", q.Name)
	}
	for _, c := range g.commands {
		writeUnaryHandler(b, "command", c.Name)
	}
	for _, s := range g.streams {
		writeStreamHandler(b, s)
	}
	b.WriteString("\treturn cfg.wrap(mux)\n")
	b.WriteString("}\n\n")
}

func writeUnaryHandler(b *strings.Builder, kind, name string) {
	fmt.Fprintf(b, "\tmux.HandleFunc(\"POST /%s/%s\", func(w http.ResponseWriter, r *http.Request) {\n", kind, name)
	fmt.Fprintf(b, "\t\tvar req %sRequest\n", name)
	b.WriteString("\t\tif !decodeRequest(w, r, cfg.maxRequestBytes, &req) {\n\t\t\treturn\n\t\t}\n")
	fmt.Fprintf(b, "\t\tif err := validate%sRequest(req); err != nil {\n", name)
	b.WriteString("\t\t\thttp.Error(w, err.Error(), http.StatusBadRequest)\n\t\t\treturn\n\t\t}\n")
	fmt.Fprintf(b, "\t\tresult, err := impl.%s(serve.WithResponse(r.Context(), w, r), req)\n", name)
	b.WriteString("\t\tif err != nil {\n")
	b.WriteString("\t\t\thttp.Error(w, err.Error(), http.StatusInternalServerError)\n\t\t\treturn\n\t\t}\n")
	b.WriteString("\t\tw.Header().Set(\"Content-Type\", \"application/json\")\n")
	b.WriteString("\t\t_ = json.NewEncoder(w).Encode(result)\n")
	b.WriteString("\t})\n")
}

func writeStreamHandler(b *strings.Builder, s ir.Stream) {
	name := s.Name
	multi := len(s.Channels) > 0
	fmt.Fprintf(b, "\tmux.HandleFunc(\"POST /stream/%s\", func(w http.ResponseWriter, r *http.Request) {\n", name)
	fmt.Fprintf(b, "\t\tvar req %sRequest\n", name)
	b.WriteString("\t\tif !decodeRequest(w, r, cfg.maxRequestBytes, &req) {\n\t\t\treturn\n\t\t}\n")
	fmt.Fprintf(b, "\t\tif err := validate%sRequest(req); err != nil {\n", name)
	b.WriteString("\t\t\thttp.Error(w, err.Error(), http.StatusBadRequest)\n\t\t\treturn\n\t\t}\n")
	b.WriteString("\t\tfl, ok := w.(http.Flusher)\n")
	b.WriteString("\t\tif !ok {\n")
	b.WriteString("\t\t\thttp.Error(w, \"streaming unsupported\", http.StatusInternalServerError)\n\t\t\treturn\n\t\t}\n")
	if multi {
		b.WriteString("\t\tw.Header().Set(\"Content-Type\", \"application/x-ndjson\")\n")
	} else {
		b.WriteString("\t\tw.Header().Set(\"Content-Type\", \"text/plain; charset=utf-8\")\n")
	}
	b.WriteString("\t\tw.Header().Set(\"Cache-Control\", \"no-store\")\n")
	b.WriteString("\t\tw.Header().Set(\"X-Accel-Buffering\", \"no\")\n")
	b.WriteString("\t\tsw := &streamWriter{w: w, fl: fl}\n")
	fmt.Fprintf(b, "\t\tif err := impl.%s(serve.WithResponse(r.Context(), w, r), req, &%sStream{s: sw}); err != nil {\n", name, name)
	b.WriteString("\t\t\tif !sw.sawWrite() {\n")
	b.WriteString("\t\t\t\t// Failed before the first delta: a non-200 so the\n")
	b.WriteString("\t\t\t\t// client's .failed/.error cells trip.\n")
	b.WriteString("\t\t\t\thttp.Error(w, err.Error(), http.StatusBadGateway)\n")
	b.WriteString("\t\t\t\treturn\n")
	b.WriteString("\t\t\t}\n")
	if multi {
		b.WriteString("\t\t\t// Mid-stream failure: the reserved channel carries it\n")
		b.WriteString("\t\t\t// in-band; the client fails the op when it sees it.\n")
		fmt.Fprintf(b, "\t\t\t_ = sw.writeChannel(%q, err.Error())\n", ErrorChannel)
	} else {
		b.WriteString("\t\t\t// Mid-stream failure on a raw-text stream: no in-band\n")
		b.WriteString("\t\t\t// frame exists, so abort the connection uncleanly. A\n")
		b.WriteString("\t\t\t// clean return would write net/http's terminating chunk,\n")
		b.WriteString("\t\t\t// making truncation indistinguishable from success — the\n")
		b.WriteString("\t\t\t// client would resolve the stream and never trip\n")
		b.WriteString("\t\t\t// .failed/.error. ErrAbortHandler closes the connection\n")
		b.WriteString("\t\t\t// without that chunk, so the client's reader rejects.\n")
		b.WriteString("\t\t\tpanic(http.ErrAbortHandler)\n")
	}
	b.WriteString("\t\t}\n")
	b.WriteString("\t})\n")
}

// writePageHandler emits the boot-time page handler wrapper: compile
// the sigil package once (failing boot, not first request), verify
// the contract hash, serve cached bytes with compiler-derived
// security headers. The heavy lifting lives in pkg/serve.
func writePageHandler(b *strings.Builder) {
	b.WriteString(`// NewPageHandler compiles the sigil package at sigilPackageDir and
// returns a handler serving the app page at "/". Compilation happens
// once, here — a broken page fails boot, not the first request — and
// the freshly compiled package's contract hash must equal this
// file's ContractHash (regenerate with the same sigil version that
// builds this binary if it doesn't). Pass serve.WithDev() for the
// recompile-per-request dev loop.
func NewPageHandler(sigilPackageDir string, opts ...serve.PageOption) (http.Handler, error) {
	return serve.Page(sigilPackageDir, append([]serve.PageOption{serve.ExpectContract(ContractHash)}, opts...)...)
}
`)
}

// validatorsErr reports whether any generated validator actually
// returns an error (and therefore needs `fmt.Errorf`).
func validatorsErr(c contract.Contract) bool {
	for _, t := range c.Types {
		if t.Kind == "sum" {
			return true
		}
		for _, f := range t.Fields {
			if typeNeedsValidation(f.Type) {
				return true
			}
		}
	}
	for _, in := range allInputs(c) {
		if typeNeedsValidation(in.Type) {
			return true
		}
	}
	return false
}

func allInputs(c contract.Contract) []ir.TypeFieldSpec {
	var out []ir.TypeFieldSpec
	for _, q := range c.Queries {
		out = append(out, q.Inputs...)
	}
	for _, cmd := range c.Commands {
		out = append(out, cmd.Inputs...)
	}
	for _, s := range c.Streams {
		out = append(out, s.Inputs...)
	}
	return out
}

// writeValidators emits one `validate<T>` function per declared
// type and one `validate<Op>Request` per op. Request validators are
// always emitted (even when their body is `return nil`) so handler
// call sites stay uniform.
func writeValidators(b *strings.Builder, c contract.Contract) {
	for _, t := range c.Types {
		switch t.Kind {
		case "sum":
			if t.HasPayloads() {
				writeUnionValidator(b, t)
			} else {
				writeSumValidator(b, t)
			}
		case "record":
			writeRecordValidator(b, t)
		}
	}
	for _, q := range c.Queries {
		writeRequestValidator(b, q.Name, q.Inputs)
	}
	for _, cmd := range c.Commands {
		writeRequestValidator(b, cmd.Name, cmd.Inputs)
	}
	for _, s := range c.Streams {
		writeRequestValidator(b, s.Name, s.Inputs)
	}
}

// writeSumValidator emits a switch over the closed variant set,
// returning an `unknown variant` error on miss.
func writeSumValidator(b *strings.Builder, t ir.TypeDecl) {
	fmt.Fprintf(b, "func validate%s(v %s) error {\n", t.Name, t.Name)
	b.WriteString("\tswitch v {\n")
	b.WriteString("\tcase ")
	for i, v := range t.Variants {
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(b, "%s%s", t.Name, goFieldName(v))
	}
	b.WriteString(":\n")
	b.WriteString("\t\treturn nil\n")
	b.WriteString("\t}\n")
	fmt.Fprintf(b, "\treturn fmt.Errorf(\"%s: unknown variant %%q\", string(v))\n", t.Name)
	b.WriteString("}\n\n")
}

// writeUnionValidator emits a switch over a discriminated union's
// tag: unknown tags are rejected, and the active variant's payload is
// validated when its type needs it (a record / sum / list payload).
func writeUnionValidator(b *strings.Builder, t ir.TypeDecl) {
	fmt.Fprintf(b, "func validate%s(v %s) error {\n", t.Name, t.Name)
	b.WriteString("\tswitch v.Tag {\n")
	for _, vs := range t.VariantSpecs {
		fmt.Fprintf(b, "\tcase %q:\n", vs.Name)
		if vs.Payload == nil || !typeNeedsValidation(*vs.Payload) {
			continue
		}
		field := goFieldName(vs.Name)
		access := "v." + field
		if isList(*vs.Payload) {
			inner := vs.Payload.GenericArgs[0]
			if !typeNeedsValidation(inner) || isList(inner) {
				continue
			}
			fmt.Fprintf(b, "\t\tif %s != nil {\n", access)
			fmt.Fprintf(b, "\t\t\tfor i, elem := range *%s {\n", access)
			fmt.Fprintf(b, "\t\t\t\tif err := validate%s(elem); err != nil {\n", inner.Name)
			fmt.Fprintf(b, "\t\t\t\t\treturn fmt.Errorf(\"%s.%s[%%d]: %%w\", i, err)\n", t.Name, vs.Name)
			b.WriteString("\t\t\t\t}\n\t\t\t}\n\t\t}\n")
			continue
		}
		fmt.Fprintf(b, "\t\tif %s != nil {\n", access)
		fmt.Fprintf(b, "\t\t\tif err := validate%s(*%s); err != nil {\n", vs.Payload.Name, access)
		fmt.Fprintf(b, "\t\t\t\treturn fmt.Errorf(\"%s.%s: %%w\", err)\n", t.Name, vs.Name)
		b.WriteString("\t\t\t}\n\t\t}\n")
	}
	b.WriteString("\tdefault:\n")
	fmt.Fprintf(b, "\t\treturn fmt.Errorf(\"%s: unknown tag %%q\", v.Tag)\n", t.Name)
	b.WriteString("\t}\n\treturn nil\n}\n\n")
}

// writeRecordValidator emits a function that validates each field
// whose type needs validation (sum / nested record / list of either).
func writeRecordValidator(b *strings.Builder, t ir.TypeDecl) {
	fmt.Fprintf(b, "func validate%s(v %s) error {\n", t.Name, t.Name)
	for _, f := range t.Fields {
		writeFieldValidation(b, "v", t.Name, f, "\t")
	}
	b.WriteString("\treturn nil\n")
	b.WriteString("}\n\n")
}

// writeRequestValidator emits validate<Op>Request. Same shape as a
// record validator; always emitted because handlers always call it.
func writeRequestValidator(b *strings.Builder, opName string, inputs []ir.TypeFieldSpec) {
	fmt.Fprintf(b, "func validate%sRequest(v %sRequest) error {\n", opName, opName)
	for _, f := range inputs {
		writeFieldValidation(b, "v", opName+"Request", f, "\t")
	}
	b.WriteString("\treturn nil\n")
	b.WriteString("}\n\n")
}

// writeFieldValidation emits zero-or-more lines that validate one
// field of `target` (a Go variable name). See writeValueValidation
// for the per-shape split.
func writeFieldValidation(b *strings.Builder, target, parent string, f ir.TypeFieldSpec, indent string) {
	if !typeNeedsValidation(f.Type) {
		return
	}
	access := target + "." + goFieldName(f.Name)
	if f.Type.Optional && !isList(f.Type) {
		fmt.Fprintf(b, "%sif %s != nil {\n", indent, access)
		writeValueValidation(b, "(*"+access+")", parent, f.Name, dropOptional(f.Type), indent+"\t")
		fmt.Fprintf(b, "%s}\n", indent)
		return
	}
	writeValueValidation(b, access, parent, f.Name, f.Type, indent)
}

// writeValueValidation emits the validation code for one already-
// addressed value: declared = one validate<T> call; List<P> = range
// loop with the index threaded into the error path. Nested lists in
// a single field aren't realistic at v0 — the inner is treated as
// primitive when it is itself a list.
func writeValueValidation(b *strings.Builder, expr, parent, fieldPath string, t ir.TypeRef, indent string) {
	if isList(t) {
		inner := t.GenericArgs[0]
		if !typeNeedsValidation(inner) || isList(inner) {
			return
		}
		fmt.Fprintf(b, "%sfor i, elem := range %s {\n", indent, expr)
		fmt.Fprintf(b, "%s\tif err := validate%s(elem); err != nil {\n", indent, inner.Name)
		fmt.Fprintf(b, "%s\t\treturn fmt.Errorf(\"%s.%s[%%d]: %%w\", i, err)\n", indent, parent, fieldPath)
		fmt.Fprintf(b, "%s\t}\n", indent)
		fmt.Fprintf(b, "%s}\n", indent)
		return
	}
	fmt.Fprintf(b, "%sif err := validate%s(%s); err != nil {\n", indent, t.Name, expr)
	fmt.Fprintf(b, "%s\treturn fmt.Errorf(\"%s.%s: %%w\", err)\n", indent, parent, fieldPath)
	fmt.Fprintf(b, "%s}\n", indent)
}

// typeNeedsValidation reports whether a TypeRef carries any
// validatable shape: declared types always do, lists need it iff
// their element type does, primitives never do.
func typeNeedsValidation(t ir.TypeRef) bool {
	switch t.Name {
	case "Int", "String", "Bool":
		return false
	case "List":
		if len(t.GenericArgs) == 1 {
			return typeNeedsValidation(t.GenericArgs[0])
		}
		return false
	}
	return true
}

func isList(t ir.TypeRef) bool {
	return t.Name == "List" && len(t.GenericArgs) == 1
}

func dropOptional(t ir.TypeRef) ir.TypeRef {
	t.Optional = false
	return t
}

// goType renders an ir.TypeRef as a Go type expression. Slices
// stay []T even when optional — slices are already nilable, so
// *[]T would be redundant indirection.
func goType(t ir.TypeRef) string {
	if t.Name == "List" && len(t.GenericArgs) == 1 {
		return "[]" + goType(t.GenericArgs[0])
	}
	base := goBaseType(t.Name)
	if t.Optional {
		return "*" + base
	}
	return base
}

// goBaseType maps Sigil primitive names to Go equivalents.
// Declared types pass through unchanged.
func goBaseType(name string) string {
	switch name {
	case "Int":
		return "int64"
	case "String":
		return "string"
	case "Bool":
		return "bool"
	}
	return name
}

// goFieldName capitalizes the first rune so the field exports.
func goFieldName(name string) string {
	if name == "" {
		return ""
	}
	return strings.ToUpper(name[:1]) + name[1:]
}

// jsonTagSuffix returns `,omitempty` for optionals so a nil
// pointer doesn't serialize as `"name":null`.
func jsonTagSuffix(t ir.TypeRef) string {
	if t.Optional && !(t.Name == "List" && len(t.GenericArgs) == 1) {
		return ",omitempty"
	}
	return ""
}
