// Code generated by sigil gen. DO NOT EDIT.
package conformance

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"sync"

	"github.com/incantery/mako/pkg/serve"
)

// ContractHash is the wire-shape digest of the sigil contract this
// file was generated from. NewPageHandler verifies the compiled
// package still matches it at boot.
const ContractHash = "c1:62456b9b254de0f9f817b25042422b395e920fca767692bdf6cf09fb41ec3c10"

type ChatDelta struct {
	Thinking string `json:"thinking"`
	Answer   string `json:"answer"`
}

type Mode string

const (
	ModeFast Mode = "fast"
	ModeDeep Mode = "deep"
)

type User struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

// LoginOutcome is a discriminated union: exactly one variant is set,
// named by Tag. Build it with the NewLoginOutcome* constructors.
type LoginOutcome struct {
	Tag     string
	Success *User
	Invalid *string
}

func NewLoginOutcomeIdle() LoginOutcome { return LoginOutcome{Tag: "idle"} }

func NewLoginOutcomeSuccess(v User) LoginOutcome { return LoginOutcome{Tag: "success", Success: &v} }

func NewLoginOutcomeInvalid(v string) LoginOutcome { return LoginOutcome{Tag: "invalid", Invalid: &v} }

func NewLoginOutcomeLocked() LoginOutcome { return LoginOutcome{Tag: "locked"} }

func (u LoginOutcome) MarshalJSON() ([]byte, error) {
	var value any
	switch u.Tag {
	case "idle":
	case "success":
		if u.Success != nil {
			value = *u.Success
		}
	case "invalid":
		if u.Invalid != nil {
			value = *u.Invalid
		}
	case "locked":
	default:
		return nil, fmt.Errorf("LoginOutcome: unknown tag %q", u.Tag)
	}
	return json.Marshal(struct {
		Tag   string `json:"tag"`
		Value any    `json:"value,omitempty"`
	}{u.Tag, value})
}

func (u *LoginOutcome) UnmarshalJSON(data []byte) error {
	var w struct {
		Tag   string          `json:"tag"`
		Value json.RawMessage `json:"value"`
	}
	if err := json.Unmarshal(data, &w); err != nil {
		return err
	}
	u.Tag = w.Tag
	switch w.Tag {
	case "idle":
	case "success":
		var v User
		if len(w.Value) > 0 {
			if err := json.Unmarshal(w.Value, &v); err != nil {
				return err
			}
		}
		u.Success = &v
	case "invalid":
		var v string
		if len(w.Value) > 0 {
			if err := json.Unmarshal(w.Value, &v); err != nil {
				return err
			}
		}
		u.Invalid = &v
	case "locked":
	default:
		return fmt.Errorf("LoginOutcome: unknown tag %q", w.Tag)
	}
	return nil
}

type ListModesRequest struct{}

type SetModeRequest struct {
	Mode Mode `json:"mode"`
}

type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type ChatRequest struct {
	Prompt string `json:"prompt"`
}

type TailRequest struct {
	Path string `json:"path"`
}

// streamWriter is the shared low-level delta writer behind every
// typed stream sender. Write order is serialized; wrote flips on the
// first delta and decides the error mapping (502 before the first
// delta, in-band after).
type streamWriter struct {
	w     http.ResponseWriter
	fl    http.Flusher
	mu    sync.Mutex
	wrote bool
}

func (s *streamWriter) writeChannel(channel, text string) error {
	b, err := json.Marshal(struct {
		Channel string `json:"channel"`
		Text    string `json:"text"`
	}{channel, text})
	if err != nil {
		return err
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	s.wrote = true
	if _, err := s.w.Write(append(b, '\n')); err != nil {
		return err
	}
	s.fl.Flush()
	return nil
}

func (s *streamWriter) writeRaw(text string) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.wrote = true
	if _, err := s.w.Write([]byte(text)); err != nil {
		return err
	}
	s.fl.Flush()
	return nil
}

func (s *streamWriter) sawWrite() bool {
	s.mu.Lock()
	defer s.mu.Unlock()
	return s.wrote
}

// ChatStream sends Chat deltas. Each method writes one NDJSON line
// tagged with its channel and flushes it to the client.
type ChatStream struct {
	s *streamWriter
}

func (s *ChatStream) Thinking(text string) error {
	return s.s.writeChannel("thinking", text)
}

func (s *ChatStream) Answer(text string) error {
	return s.s.writeChannel("answer", text)
}

// TailStream sends Tail deltas: raw text chunks, appended verbatim
// by the client.
type TailStream struct {
	s *streamWriter
}

func (s *TailStream) Send(text string) error {
	return s.s.writeRaw(text)
}

// Api is the server contract for every op routed through the
// "Api" backend. Implement it, then mount NewApiHandler.
type Api interface {
	ListModes(ctx context.Context, req ListModesRequest) ([]string, error)
	SetMode(ctx context.Context, req SetModeRequest) (bool, error)
	Login(ctx context.Context, req LoginRequest) (LoginOutcome, error)
	Chat(ctx context.Context, req ChatRequest, stream *ChatStream) error
	Tail(ctx context.Context, req TailRequest, stream *TailStream) error
}

func validateChatDelta(v ChatDelta) error {
	return nil
}

func validateMode(v Mode) error {
	switch v {
	case ModeFast, ModeDeep:
		return nil
	}
	return fmt.Errorf("Mode: unknown variant %q", string(v))
}

func validateUser(v User) error {
	return nil
}

func validateLoginOutcome(v LoginOutcome) error {
	switch v.Tag {
	case "idle":
	case "success":
		if v.Success != nil {
			if err := validateUser(*v.Success); err != nil {
				return fmt.Errorf("LoginOutcome.success: %w", err)
			}
		}
	case "invalid":
	case "locked":
	default:
		return fmt.Errorf("LoginOutcome: unknown tag %q", v.Tag)
	}
	return nil
}

func validateListModesRequest(v ListModesRequest) error {
	return nil
}

func validateSetModeRequest(v SetModeRequest) error {
	if err := validateMode(v.Mode); err != nil {
		return fmt.Errorf("SetModeRequest.mode: %w", err)
	}
	return nil
}

func validateLoginRequest(v LoginRequest) error {
	return nil
}

func validateChatRequest(v ChatRequest) error {
	return nil
}

func validateTailRequest(v TailRequest) error {
	return nil
}

// HandlerOption configures a generated handler.
type HandlerOption func(*handlerConfig)

type handlerConfig struct {
	middleware      []func(http.Handler) http.Handler
	maxRequestBytes int64
}

// WithMiddleware wraps the whole handler. Options apply outermost
// first: WithMiddleware(a), WithMiddleware(b) yields a(b(handler)).
func WithMiddleware(mw func(http.Handler) http.Handler) HandlerOption {
	return func(c *handlerConfig) { c.middleware = append(c.middleware, mw) }
}

// WithMaxRequestBytes caps op request bodies (default 1 MiB).
func WithMaxRequestBytes(n int64) HandlerOption {
	return func(c *handlerConfig) { c.maxRequestBytes = n }
}

func newHandlerConfig(opts []HandlerOption) handlerConfig {
	cfg := handlerConfig{maxRequestBytes: 1 << 20}
	for _, o := range opts {
		o(&cfg)
	}
	return cfg
}

func (c handlerConfig) wrap(h http.Handler) http.Handler {
	for i := len(c.middleware) - 1; i >= 0; i-- {
		h = c.middleware[i](h)
	}
	return h
}

// decodeRequest decodes + caps one op request body. A false return
// means the 400 response was already written.
func decodeRequest(w http.ResponseWriter, r *http.Request, maxBytes int64, into any) bool {
	r.Body = http.MaxBytesReader(w, r.Body, maxBytes)
	if err := json.NewDecoder(r.Body).Decode(into); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return false
	}
	return true
}

// NewApiHandler returns the HTTP handler implementing the wire
// contract for Api's ops. Mount it wherever your mux routes
// /query/, /command/, and /stream/ paths.
func NewApiHandler(impl Api, opts ...HandlerOption) http.Handler {
	cfg := newHandlerConfig(opts)
	mux := http.NewServeMux()
	mux.HandleFunc("POST /query/ListModes", func(w http.ResponseWriter, r *http.Request) {
		var req ListModesRequest
		if !decodeRequest(w, r, cfg.maxRequestBytes, &req) {
			return
		}
		if err := validateListModesRequest(req); err != nil {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}
		result, err := impl.ListModes(serve.WithResponse(r.Context(), w, r), req)
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(result)
	})
	mux.HandleFunc("POST /command/SetMode", func(w http.ResponseWriter, r *http.Request) {
		var req SetModeRequest
		if !decodeRequest(w, r, cfg.maxRequestBytes, &req) {
			return
		}
		if err := validateSetModeRequest(req); err != nil {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}
		result, err := impl.SetMode(serve.WithResponse(r.Context(), w, r), req)
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(result)
	})
	mux.HandleFunc("POST /command/Login", func(w http.ResponseWriter, r *http.Request) {
		var req LoginRequest
		if !decodeRequest(w, r, cfg.maxRequestBytes, &req) {
			return
		}
		if err := validateLoginRequest(req); err != nil {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}
		result, err := impl.Login(serve.WithResponse(r.Context(), w, r), req)
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(result)
	})
	mux.HandleFunc("POST /stream/Chat", func(w http.ResponseWriter, r *http.Request) {
		var req ChatRequest
		if !decodeRequest(w, r, cfg.maxRequestBytes, &req) {
			return
		}
		if err := validateChatRequest(req); err != nil {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}
		fl, ok := w.(http.Flusher)
		if !ok {
			http.Error(w, "streaming unsupported", http.StatusInternalServerError)
			return
		}
		w.Header().Set("Content-Type", "application/x-ndjson")
		w.Header().Set("Cache-Control", "no-store")
		w.Header().Set("X-Accel-Buffering", "no")
		sw := &streamWriter{w: w, fl: fl}
		if err := impl.Chat(serve.WithResponse(r.Context(), w, r), req, &ChatStream{s: sw}); err != nil {
			if !sw.sawWrite() {
				// Failed before the first delta: a non-200 so the
				// client's .failed/.error cells trip.
				http.Error(w, err.Error(), http.StatusBadGateway)
				return
			}
			// Mid-stream failure: the reserved channel carries it
			// in-band; the client fails the op when it sees it.
			_ = sw.writeChannel("__error", err.Error())
		}
	})
	mux.HandleFunc("POST /stream/Tail", func(w http.ResponseWriter, r *http.Request) {
		var req TailRequest
		if !decodeRequest(w, r, cfg.maxRequestBytes, &req) {
			return
		}
		if err := validateTailRequest(req); err != nil {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}
		fl, ok := w.(http.Flusher)
		if !ok {
			http.Error(w, "streaming unsupported", http.StatusInternalServerError)
			return
		}
		w.Header().Set("Content-Type", "text/plain; charset=utf-8")
		w.Header().Set("Cache-Control", "no-store")
		w.Header().Set("X-Accel-Buffering", "no")
		sw := &streamWriter{w: w, fl: fl}
		if err := impl.Tail(serve.WithResponse(r.Context(), w, r), req, &TailStream{s: sw}); err != nil {
			if !sw.sawWrite() {
				// Failed before the first delta: a non-200 so the
				// client's .failed/.error cells trip.
				http.Error(w, err.Error(), http.StatusBadGateway)
				return
			}
			// Mid-stream failure on a raw-text stream: no in-band
			// frame exists, so abort the connection uncleanly. A
			// clean return would write net/http's terminating chunk,
			// making truncation indistinguishable from success — the
			// client would resolve the stream and never trip
			// .failed/.error. ErrAbortHandler closes the connection
			// without that chunk, so the client's reader rejects.
			panic(http.ErrAbortHandler)
		}
	})
	return cfg.wrap(mux)
}

// NewPageHandler compiles the sigil package at sigilPackageDir and
// returns a handler serving the app page at "/". Compilation happens
// once, here — a broken page fails boot, not the first request — and
// the freshly compiled package's contract hash must equal this
// file's ContractHash (regenerate with the same sigil version that
// builds this binary if it doesn't). Pass serve.WithDev() for the
// recompile-per-request dev loop.
func NewPageHandler(sigilPackageDir string, opts ...serve.PageOption) (http.Handler, error) {
	return serve.Page(sigilPackageDir, append([]serve.PageOption{serve.ExpectContract(ContractHash)}, opts...)...)
}
