package cli

import (
	"fmt"
	"os"

	"github.com/spf13/cobra"

	"github.com/incantery/sigil/pkg/gen"

	// Generator targets register themselves into pkg/gen's registry.
	_ "github.com/incantery/sigil/pkg/codegen/gogen"
)

var genCmd = &cobra.Command{
	Use:   "gen",
	Short: "Run code generation as configured in sigil.gen.yaml",
	Long: `Runs every entry in the module's sigil.gen.yaml — the committed,
buf.gen.yaml-style config that lives next to sigil.mod:

    version: 1
    generate:
      - target: go
        package: app/chat
        out: internal/gen/chat

Each entry compiles one sigil package, extracts its contract (the
backends, query/command/stream ops, and types — the IDL), and hands
it to the named generator target. Generated output is meant to be
gitignored and regenerated by your build (e.g. a make gen target
running the pinned sigil CLI), never edited.

There are no flags and no arguments: the config file is the only way
to invoke generation, so your checkout, your teammate's, and CI
produce identical output by construction.`,
	Args: cobra.NoArgs,
	RunE: func(cmd *cobra.Command, args []string) error {
		cwd, err := os.Getwd()
		if err != nil {
			return err
		}
		logf := func(format string, a ...any) {
			fmt.Fprintf(cmd.OutOrStdout(), format+"\n", a...)
		}
		if err := gen.Run(cwd, logf); err != nil {
			fmt.Fprintln(os.Stderr, err.Error())
			return ErrSilent
		}
		return nil
	},
}
