// Code generated by sigil. DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
)

type Mood string

const (
	MoodCalm Mood = "calm"
	MoodExcited Mood = "excited"
	MoodGrumpy Mood = "grumpy"
)

type Slot struct {
	Id int64 `json:"id"`
	Name string `json:"name"`
	Hp int64 `json:"hp"`
}

type PingArgs struct{}

type GetTeamSizeArgs struct{}

type GetActiveNameArgs struct{}

type GetSlotArgs struct {
	Id int64 `json:"id"`
}

type TrainArgs struct{}

type CatchPokemonArgs struct {
	Id int64 `json:"id"`
}

type SetMoodArgs struct {
	Mood Mood `json:"mood"`
}

// API is the server contract for every declared query and command.
// Implement this on a user-defined struct, then call Mount to wire
// HTTP handlers to its methods.
type API interface {
	Ping(ctx context.Context, args PingArgs) (bool, error)
	GetTeamSize(ctx context.Context, args GetTeamSizeArgs) (int64, error)
	GetActiveName(ctx context.Context, args GetActiveNameArgs) (string, error)
	GetSlot(ctx context.Context, args GetSlotArgs) (Slot, error)
	Train(ctx context.Context, args TrainArgs) (bool, error)
	CatchPokemon(ctx context.Context, args CatchPokemonArgs) (bool, error)
	SetMood(ctx context.Context, args SetMoodArgs) (bool, error)
}

func validateMood(v Mood) error {
	switch v {
	case MoodCalm, MoodExcited, MoodGrumpy:
		return nil
	}
	return fmt.Errorf("Mood: unknown variant %q", string(v))
}

func validateSlot(v Slot) error {
	return nil
}

func validatePingArgs(v PingArgs) error {
	return nil
}

func validateGetTeamSizeArgs(v GetTeamSizeArgs) error {
	return nil
}

func validateGetActiveNameArgs(v GetActiveNameArgs) error {
	return nil
}

func validateGetSlotArgs(v GetSlotArgs) error {
	return nil
}

func validateTrainArgs(v TrainArgs) error {
	return nil
}

func validateCatchPokemonArgs(v CatchPokemonArgs) error {
	return nil
}

func validateSetMoodArgs(v SetMoodArgs) error {
	if err := validateMood(v.Mood); err != nil {
		return fmt.Errorf("SetMoodArgs.mood: %w", err)
	}
	return nil
}

// Mount registers one POST handler per declared op on the supplied mux.
// Queries land at /query/<Name>, commands at /command/<Name>; both
// expect JSON request bodies decodable into the op's Args struct and
// respond with JSON-encoded results.
func Mount(api API, mux *http.ServeMux) {
	mux.HandleFunc("POST /query/Ping", func(w http.ResponseWriter, r *http.Request) {
		var args PingArgs
		if err := json.NewDecoder(r.Body).Decode(&args); err != nil {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}
		if err := validatePingArgs(args); err != nil {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}
		result, err := api.Ping(r.Context(), args)
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(result)
	})
	mux.HandleFunc("POST /query/GetTeamSize", func(w http.ResponseWriter, r *http.Request) {
		var args GetTeamSizeArgs
		if err := json.NewDecoder(r.Body).Decode(&args); err != nil {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}
		if err := validateGetTeamSizeArgs(args); err != nil {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}
		result, err := api.GetTeamSize(r.Context(), args)
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(result)
	})
	mux.HandleFunc("POST /query/GetActiveName", func(w http.ResponseWriter, r *http.Request) {
		var args GetActiveNameArgs
		if err := json.NewDecoder(r.Body).Decode(&args); err != nil {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}
		if err := validateGetActiveNameArgs(args); err != nil {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}
		result, err := api.GetActiveName(r.Context(), args)
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(result)
	})
	mux.HandleFunc("POST /query/GetSlot", func(w http.ResponseWriter, r *http.Request) {
		var args GetSlotArgs
		if err := json.NewDecoder(r.Body).Decode(&args); err != nil {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}
		if err := validateGetSlotArgs(args); err != nil {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}
		result, err := api.GetSlot(r.Context(), args)
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(result)
	})
	mux.HandleFunc("POST /command/Train", func(w http.ResponseWriter, r *http.Request) {
		var args TrainArgs
		if err := json.NewDecoder(r.Body).Decode(&args); err != nil {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}
		if err := validateTrainArgs(args); err != nil {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}
		result, err := api.Train(r.Context(), args)
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(result)
	})
	mux.HandleFunc("POST /command/CatchPokemon", func(w http.ResponseWriter, r *http.Request) {
		var args CatchPokemonArgs
		if err := json.NewDecoder(r.Body).Decode(&args); err != nil {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}
		if err := validateCatchPokemonArgs(args); err != nil {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}
		result, err := api.CatchPokemon(r.Context(), args)
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(result)
	})
	mux.HandleFunc("POST /command/SetMood", func(w http.ResponseWriter, r *http.Request) {
		var args SetMoodArgs
		if err := json.NewDecoder(r.Body).Decode(&args); err != nil {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}
		if err := validateSetMoodArgs(args); err != nil {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}
		result, err := api.SetMood(r.Context(), args)
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(result)
	})
}
